import sys
sys.path.append("..")

from matrix import Matrix
from texture import Texture

#example code to use Matrix() object to create a musical texture...
print("Let's create a musical texture...", end="\n")

#some configuration data...
title = "Fantastic piece"
composer = "The computer"
key = 0
t_sig = "3/4"
cycles = 1
mode = "filled" #you can use filled, puntual and mobile...
t_unit = 0.5 #minimum duration (quarter note fraction)... 
t_measure = 3 #whole measure duration (quarter notes)...
offs = 72 #midi offset for upper voice...
v_offs = -12 #midi offset for each part...
name = "texture"

#we need a Matrix()
the_matrix = Matrix(12, "") #we start an empty matrix...
the_matrix.translation_cycle("0 2-5 9-7 1", 4) #we build a matrix by translation cycles...
the_matrix.print_matrix() #we want to see it!

for i in range(3):
	t = Texture(title, composer, key, t_sig, the_matrix, cycles, mode, t_unit, t_measure, offs, v_offs)
	for j in range(3):
		t.matrix.shuffle_status() #we shuffle the matrix...
		t.matrix.translation(0) #we translate the matrix...
		t.add_cycle() #we add a complete new cycle...
	filename = name + "_" + str(i)
	t.save_score("output/", filename, "xml")
