import sys
sys.path.append("..")

from counterpoint import Counterpoint

#example code create music with Counterpoint()...
print("Let's create a musical counterpoint...", end="\n")

#some configuration data...
title = "Fantastic piece"
composer = "The computer"
key = 0
t_sig = "3/4"
parts = 6 #the number of voices...
cycles = 10 #the number of initial cycles...
mode = "markov" #you can use random, filled, puntual, mobile, conditional, control and markov...
markov_path = "data/markov_repeat_table.json" #markov table file...
data = "0 2 3-5 7-9 1-8 7 4" #input data for selected mode...
t_unit = 0.5 #minimum duration (quarter note fraction)... 
t_measure = 3 #whole measure duration (quarter notes)...
offs = 84 #midi offset for upper voice...
v_offs = -12 #midi offset for each part...
name = "counterpoint_mk_r"

for i in range(1):
	c = Counterpoint(title, composer, key, t_sig, parts, cycles, mode, markov_path, data, t_unit, t_measure, offs, v_offs)
	filename = name + "_" + str(i)
	c.save_score("output/", filename, "xml")
