import sys
sys.path.append("..")

from counterpoint import Counterpoint

#example code create music with Counterpoint()...
print("Let's create a musical counterpoint...", end="\n")

#some configuration data...
title = "Fantastic piece"
composer = "The computer"
key = 0
t_sig = "3/4"
parts = 3 #the number of voices...
cycles = 3 #the number of initial cycles...
mode = "markov" #you can use filled, puntual and mobile...
data = "0 1 2-5 8 6-0 11 10-9 8 6-0 1 2-0" #input data for selected mode...
t_unit = 0.5 #minimum duration (quarter note fraction)... 
t_measure = 3 #whole measure duration (quarter notes)...
offs = 72 #midi offset for upper voice...
v_offs = -12 #midi offset for each part...
name = "counterpoint_mk"

for i in range(1):
	c = Counterpoint(title, composer, key, t_sig, parts, cycles, mode, data, t_unit, t_measure, offs, v_offs)
	filename = name + "_" + str(i) + ".xml"
	c.save_score("output/", filename, "xml")
