#first we add the parent folder to the path to use our tools...
import sys
sys.path.append("..")

from pcs import PCS

#example code to use PCS()...
tool = PCS() #we instance the class to load pitch class set database...
print("Let's use PCS() functions...", end="\n")

string_set = "0 1 3 7 9" #a string containing notes separated by spaces...
int_set = [0,1,3,7,9] #a list containing notes as integers...

#to get all data for a pitch class set you can call...
cardinality, ordinal, position, inverted, z_pair, states, o_form, p_form = tool.get_set_info(string_set)

#now we print all the data...
print("\nYou give me the set (" + string_set + "). I get this data:", end="\n")
print("- Number of elements: " + str(cardinality), end="\n") #cardinality is a number...
print("- Position in Forte's list: " + str(ordinal), end="\n") #ordinal is a number...
print("- Prime form: " + tool.notes_to_string(p_form), end="\n") #prime_form is a list...
print("- Ordered form: " + tool.notes_to_string(o_form), end="\n") #ordered_form is a list...
print("- Translation: " + str(position), end="\n") #distance between 0 and first element of ordered_form...
print("- Z-pair: " + str(cardinality) + ".Z" + str(z_pair), end="\n") #z_pair is the ordinal of the z pair...
print("- Is your set inverted?: " + str(inverted), end="\n") #inverted is a boolean...
print("- Number of states: " + str(states), end="\n\n") #total number of different states for your set...

#you can get a string with all the data too...
print(tool.build_set_info_msg(cardinality, ordinal, position, inverted, z_pair, states, o_form, p_form))

#the cardinality is given, so perhaps you want the ordinal...
ordinal = tool.get_set_ordinal(int_set)
print("I get this ordinal: " + str(ordinal), end="\n\n")

#if you want the ordered form of your set...
o_form = tool.ordered_form(int_set)
print("I ordered your set: " + tool.notes_to_string(o_form), end="\n\n")

#obvioulsy you can ask for a prime form...
p_form = tool.prime_form(int_set)
print("I looked for the prime form: " + tool.notes_to_string(p_form), end="\n\n")

#if you want to know is your set is inverted next function is better...
#you need to pass the cardinality, False (you assume is not inverted) and your prime form...
is_inverted, ordinal = tool.search_set(len(int_set), False, tool.prime_form(int_set))
if is_inverted:
	print("Your set is " + str(len(int_set)) + "." + str(ordinal) + "i", end="\n\n")
else:
	print("Your set is " + str(len(int_set)) + "." + str(ordinal), end="\n\n")

#you can calculate an interval vector for any set of notes...
i_vector = tool.interval_vector(int_set)
print("I got the interval vector " + tool.vector_to_string(i_vector), end="\n\n")
#note that this function doesn't need a valid pitch class set...
i_vector = tool.interval_vector([0,2,4,8,2,2])
print("I got the strange vector " + tool.vector_to_string(i_vector), end="\n\n")
#and if you want an interval vector with 11 pitch classes...
i_vector = tool.big_interval_vector(int_set)
print("I got the big interval vector " + tool.vector_to_string(i_vector), end="\n\n")

#finally you can invert or transate your set...
new_state = tool.translate_set(int_set, 5)
print("I got this new state for your set: " + tool.notes_to_string(new_state), end="\n")
new_state = tool.invert_set(int_set)
print("I inverted your set: " + tool.notes_to_string(new_state), end="\n\n")

#enough
print("That's all!", end="\n")
